# your_workspace/Cargo.toml
[workspace]
members = [
    "sf_core",
    "odbc",
    "jdbc_bridge",
    "proto_generator",
    "proto_utils",
    "sf_core/tests/common/arrow_deserialize_macro",
]
resolver = "1"
