# your_workspace/Cargo.toml
[workspace]
members = [
    "sf_core",
    "sf_mini_core",
    "odbc",
    "jdbc_bridge",
    "proto_generator",
    "proto_utils",
    "sf_core/tests/common/arrow_deserialize_macro",
]
resolver = "1"

[profile.release]
strip = true
opt-level = "z"
lto = true
