[package]
name = "sf_core"
version = "0.1.0"
rust_version = "1.87.0"
edition = "2024"

[lib]
name = "sf_core"
crate-type = ["dylib", "rlib"]

[dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
rand = "0.9.1"
thrift = "0.17.0"
lazy_static = "1.5.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
base64 = "0.22.1"
arrow-ipc = "55.1.0"
arrow = { version = "55.1.0", features = ["ffi"] }

