name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Generate thrift
      #   uses: ./.github/actions/generate-thrift

      # - name: Check thrift files are up-to-date
      #   run: git diff --exit-code

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check
        run: cargo check --workspace

      - name: Build
        run: cargo build --workspace

      - name: Decode secrets
        run: ./scripts/decode_secrets.sh

      - name: Test
        run: cargo test --workspace

      - name: Run code coverage
        uses: ./.github/actions/rust-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Not required for public repos
          files: ./coverage/lcov.info
          fail_ci_if_error: false
