name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev thrift-compiler

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify generated thrift files are up-to-date
        run: |
          bash ./scripts/generate_thrift.sh
          git diff --exit-code

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check
        run: cargo check --workspace

      - name: Build
        run: cargo build --workspace

      - name: Test
        run: cargo test --workspace

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --version 0.32.8

      - name: Run code coverage
        run: cargo tarpaulin --workspace --out Lcov --output-dir ./coverage/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Not required for public repos
          files: ./coverage/lcov.info
          fail_ci_if_error: false