name: JDBC CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  jdbc_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: ['8']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Decode secrets
        run: ./scripts/decode_secrets.sh
        env:
          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}

      - name: Build Rust components
        run: |
          cargo build --package sf_core
          cargo build --package jdbc_bridge

      - name: Make gradlew executable
        run: chmod +x jdbc/gradlew

      - name: Run JDBC tests
        run: |
          ls -l target/debug/
          export PARAMETER_PATH=$(pwd)/parameters.json
          export CORE_PATH=$(pwd)/target/debug/libjdbc_bridge.so
          cd jdbc
          ./gradlew test jacocoTestReport --stacktrace

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.SNOW_CODECOV_TOKEN }}
        with:
          files: ./jdbc/build/reports/jacoco/test/jacocoTestReport.xml
          flags: jdbc
          name: jdbc-${{ runner.os }}-java${{ matrix.java-version }}
          fail_ci_if_error: false